//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class EFMovie
{
    public string Title { get; set; }
    public string Director { get; set; }
    public int Genre { get; set; }
    public int Runtime { get; set; }
    public System.DateTime ReleaseDate { get; set; }
}
