'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property AddressID As Integer
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property StateProvince As String
    Public Property CountryRegion As String
    Public Property PostalCode As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property CustomerAddresses As ICollection(Of CustomerAddress) = New HashSet(Of CustomerAddress)
    Public Overridable Property SalesOrderHeaders As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)
    Public Overridable Property SalesOrderHeaders1 As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)

End Class
