'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AdventureWorksEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AdventureWorksEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property BuildVersions() As DbSet(Of BuildVersion)
    Public Property ErrorLogs() As DbSet(Of ErrorLog)
    Public Property Addresses() As DbSet(Of Address)
    Public Property Customers() As DbSet(Of Customer)
    Public Property CustomerAddresses() As DbSet(Of CustomerAddress)
    Public Property Products() As DbSet(Of Product)
    Public Property ProductCategories() As DbSet(Of ProductCategory)
    Public Property ProductDescriptions() As DbSet(Of ProductDescription)
    Public Property ProductModels() As DbSet(Of ProductModel)
    Public Property ProductModelProductDescriptions() As DbSet(Of ProductModelProductDescription)
    Public Property SalesOrderDetails() As DbSet(Of SalesOrderDetail)
    Public Property SalesOrderHeaders() As DbSet(Of SalesOrderHeader)

End Class
