'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BuildVersion
    Public Property SystemInformationID As Byte
    Public Property Database_Version As String
    Public Property VersionDate As Date
    Public Property ModifiedDate As Date

End Class
