'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ErrorLog
    Public Property ErrorLogID As Integer
    Public Property ErrorTime As Date
    Public Property UserName As String
    Public Property ErrorNumber As Integer
    Public Property ErrorSeverity As Nullable(Of Integer)
    Public Property ErrorState As Nullable(Of Integer)
    Public Property ErrorProcedure As String
    Public Property ErrorLine As Nullable(Of Integer)
    Public Property ErrorMessage As String

End Class
