'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductModelProductDescription
    Public Property ProductModelID As Integer
    Public Property ProductDescriptionID As Integer
    Public Property Culture As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property ProductDescription As ProductDescription
    Public Overridable Property ProductModel As ProductModel

End Class
