'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SalesOrderDetail
    Public Property SalesOrderID As Integer
    Public Property SalesOrderDetailID As Integer
    Public Property OrderQty As Short
    Public Property ProductID As Integer
    Public Property UnitPrice As Decimal
    Public Property UnitPriceDiscount As Decimal
    Public Property LineTotal As Decimal
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Product As Product
    Public Overridable Property SalesOrderHeader As SalesOrderHeader

End Class
