'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EFMovie
    Public Property Title As String
    Public Property Director As String
    Public Property Genre As Nullable(Of Integer)
    Public Property Runtime As Nullable(Of Integer)
    Public Property ReleaseDate As Nullable(Of Date)

End Class
