'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Department
    Public Property DepartmentID As Short
    Public Property Name As String
    Public Property GroupName As String
    Public Property ModifiedDate As Date

    Public Overridable Property EmployeeDepartmentHistories As ICollection(Of EmployeeDepartmentHistory) = New HashSet(Of EmployeeDepartmentHistory)

End Class
