'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeeDepartmentHistory
    Public Property BusinessEntityID As Integer
    Public Property DepartmentID As Short
    Public Property ShiftID As Byte
    Public Property StartDate As Date
    Public Property EndDate As Nullable(Of Date)
    Public Property ModifiedDate As Date

    Public Overridable Property Department As Department
    Public Overridable Property Employee As Employee

End Class
