'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AdventureWorks2012_DataEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AdventureWorks2012_DataEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Employees() As DbSet(Of Employee)
    Public Property Departments() As DbSet(Of Department)
    Public Property EmployeeDepartmentHistories() As DbSet(Of EmployeeDepartmentHistory)
    Public Property EmployeePayHistories() As DbSet(Of EmployeePayHistory)

End Class
