'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property BusinessEntityID As Integer
    Public Property NationalIDNumber As String
    Public Property LoginID As String
    Public Property OrganizationLevel As Nullable(Of Short)
    Public Property JobTitle As String
    Public Property BirthDate As Date
    Public Property MaritalStatus As String
    Public Property Gender As String
    Public Property HireDate As Date
    Public Property SalariedFlag As Boolean
    Public Property VacationHours As Short
    Public Property SickLeaveHours As Short
    Public Property CurrentFlag As Boolean
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property EmployeeDepartmentHistories As ICollection(Of EmployeeDepartmentHistory) = New HashSet(Of EmployeeDepartmentHistory)
    Public Overridable Property EmployeePayHistories As ICollection(Of EmployeePayHistory) = New HashSet(Of EmployeePayHistory)

End Class
