'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeePayHistory
    Public Property BusinessEntityID As Integer
    Public Property RateChangeDate As Date
    Public Property Rate As Decimal
    Public Property PayFrequency As Byte
    Public Property ModifiedDate As Date

    Public Overridable Property Employee As Employee

End Class
