'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AdventureWorks2012_DataEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AdventureWorks2012_DataEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Customers() As DbSet(Of Customer)
    Public Property SalesOrderDetails() As DbSet(Of SalesOrderDetail)
    Public Property SalesOrderHeaders() As DbSet(Of SalesOrderHeader)
    Public Property SalesTerritories() As DbSet(Of SalesTerritory)

End Class
