'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SalesTerritory
    Public Property TerritoryID As Integer
    Public Property Name As String
    Public Property CountryRegionCode As String
    Public Property Group As String
    Public Property SalesYTD As Decimal
    Public Property SalesLastYear As Decimal
    Public Property CostYTD As Decimal
    Public Property CostLastYear As Decimal
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)
    Public Overridable Property SalesOrderHeaders As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)

End Class
