'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vendor
    Public Property BusinessEntityID As Integer
    Public Property AccountNumber As String
    Public Property Name As String
    Public Property CreditRating As Byte
    Public Property PreferredVendorStatus As Boolean
    Public Property PurchasingWebServiceURL As String
    Public Property ModifiedDate As Date

End Class
