'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property AddressID As Integer
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property StateProvince As String
    Public Property CountryRegion As String
    Public Property PostalCode As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property CustomerAddresses As ICollection(Of CustomerAddress) = New HashSet(Of CustomerAddress)
    Public Overridable Property SalesOrderHeaders As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)
    Public Overridable Property SalesOrderHeaders1 As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)

End Class
Partial Public Class BuildVersion
    Public Property SystemInformationID As Byte
    Public Property Database_Version As String
    Public Property VersionDate As Date
    Public Property ModifiedDate As Date

End Class
Partial Public Class Customer
    Public Property CustomerID As Integer
    Public Property NameStyle As Boolean
    Public Property Title As String
    Public Property FirstName As String
    Public Property MiddleName As String
    Public Property LastName As String
    Public Property Suffix As String
    Public Property CompanyName As String
    Public Property SalesPerson As String
    Public Property EmailAddress As String
    Public Property Phone As String
    Public Property PasswordHash As String
    Public Property PasswordSalt As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property CustomerAddresses As ICollection(Of CustomerAddress) = New HashSet(Of CustomerAddress)
    Public Overridable Property SalesOrderHeaders As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)

End Class
Partial Public Class CustomerAddress
    Public Property CustomerID As Integer
    Public Property AddressID As Integer
    Public Property AddressType As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Address As Address
    Public Overridable Property Customer As Customer

End Class
Partial Public Class ErrorLog
    Public Property ErrorLogID As Integer
    Public Property ErrorTime As Date
    Public Property UserName As String
    Public Property ErrorNumber As Integer
    Public Property ErrorSeverity As Nullable(Of Integer)
    Public Property ErrorState As Nullable(Of Integer)
    Public Property ErrorProcedure As String
    Public Property ErrorLine As Nullable(Of Integer)
    Public Property ErrorMessage As String

End Class
Partial Public Class Product
    Public Property ProductID As Integer
    Public Property Name As String
    Public Property ProductNumber As String
    Public Property Color As String
    Public Property StandardCost As Decimal
    Public Property ListPrice As Decimal
    Public Property Size As String
    Public Property Weight As Nullable(Of Decimal)
    Public Property ProductCategoryID As Nullable(Of Integer)
    Public Property ProductModelID As Nullable(Of Integer)
    Public Property SellStartDate As Date
    Public Property SellEndDate As Nullable(Of Date)
    Public Property DiscontinuedDate As Nullable(Of Date)
    Public Property ThumbNailPhoto As Byte()
    Public Property ThumbnailPhotoFileName As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property ProductCategory As ProductCategory
    Public Overridable Property ProductModel As ProductModel
    Public Overridable Property SalesOrderDetails As ICollection(Of SalesOrderDetail) = New HashSet(Of SalesOrderDetail)

End Class
Partial Public Class ProductCategory
    Public Property ProductCategoryID As Integer
    Public Property ParentProductCategoryID As Nullable(Of Integer)
    Public Property Name As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)
    Public Overridable Property ProductCategory1 As ICollection(Of ProductCategory) = New HashSet(Of ProductCategory)
    Public Overridable Property ProductCategory2 As ProductCategory

End Class
Partial Public Class ProductDescription
    Public Property ProductDescriptionID As Integer
    Public Property Description As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property ProductModelProductDescriptions As ICollection(Of ProductModelProductDescription) = New HashSet(Of ProductModelProductDescription)

End Class
Partial Public Class ProductModel
    Public Property ProductModelID As Integer
    Public Property Name As String
    Public Property CatalogDescription As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)
    Public Overridable Property ProductModelProductDescriptions As ICollection(Of ProductModelProductDescription) = New HashSet(Of ProductModelProductDescription)

End Class
Partial Public Class ProductModelProductDescription
    Public Property ProductModelID As Integer
    Public Property ProductDescriptionID As Integer
    Public Property Culture As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property ProductDescription As ProductDescription
    Public Overridable Property ProductModel As ProductModel

End Class
Partial Public Class SalesOrderDetail
    Public Property SalesOrderID As Integer
    Public Property SalesOrderDetailID As Integer
    Public Property OrderQty As Short
    Public Property ProductID As Integer
    Public Property UnitPrice As Decimal
    Public Property UnitPriceDiscount As Decimal
    Public Property LineTotal As Decimal
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Product As Product
    Public Overridable Property SalesOrderHeader As SalesOrderHeader

End Class
Partial Public Class SalesOrderHeader
    Public Property SalesOrderID As Integer
    Public Property RevisionNumber As Byte
    Public Property OrderDate As Date
    Public Property DueDate As Date
    Public Property ShipDate As Nullable(Of Date)
    Public Property Status As Byte
    Public Property OnlineOrderFlag As Boolean
    Public Property SalesOrderNumber As String
    Public Property PurchaseOrderNumber As String
    Public Property AccountNumber As String
    Public Property CustomerID As Integer
    Public Property ShipToAddressID As Nullable(Of Integer)
    Public Property BillToAddressID As Nullable(Of Integer)
    Public Property ShipMethod As String
    Public Property CreditCardApprovalCode As String
    Public Property SubTotal As Decimal
    Public Property TaxAmt As Decimal
    Public Property Freight As Decimal
    Public Property TotalDue As Decimal
    Public Property Comment As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Address As Address
    Public Overridable Property Address1 As Address
    Public Overridable Property Customer As Customer
    Public Overridable Property SalesOrderDetails As ICollection(Of SalesOrderDetail) = New HashSet(Of SalesOrderDetail)

End Class
